### User1 (token1) (testing app)
@token = b61cc2a8-0294-4422-a8d8-a02c2f99f183
@task-user1 = sHqgO5MBYf62TULrTlNs
@task-user2 = Jf8zVZMB6oQjLWcDaECS

### ERRORS

### Get tasks without token
# Expected error: internal code 7, status code 401
GET http://localhost:8000/tasks HTTP/2

### Get tasks with invalid token
# Expected error: internal code 5, status code 401
GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer abcdef

### Get task with invalid token
# Expected error: internal code 5, status code 401
GET http://localhost:8000/tasks/{{task-user1}} HTTP/2
Authorization: Bearer abcdef

### Get task with invalid user
# Expected error: internal code 6, status code 401
GET http://localhost:8000/tasks/{{{{task-user2}}}} HTTP/2
Authorization: Bearer {{token}}

### Get task with inexistent taskId
# Expected error: internal code 4, status code 404
GET http://localhost:8000/tasks/abc HTTP/2
Authorization: Bearer {{token}}

### Get task with invalid parameter (DELETE and PUT should work too).
# Expected error: internal code 2, status code 400 (not anymore)
# Expected error: internal code 4, status code 404
GET http://localhost:8000/tasks/a HTTP/2
Authorization: Bearer {{token}}

### Insert a task with invalid body
# Expected error: internal code 3, status code 400
POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Study HTTP",
    "description": "Read the documentation."
}

### Update a task with invalid body
# Expected error: internal code 3, status code 400
PUT http://localhost:8000/tasks/{{task-user1}} HTTP/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Study HTTP",
    "description": "Read the documentation."
}

### Update a task with invalid parameter
# Expected error: internal code 4, status code 404
# Expected error: internal code 2, status code 400 (not anymore)
PUT http://localhost:8000/tasks/a HTTP/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Update a task with missing taskId
# Expected error: internal code 1, status code 400
PUT http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Delete a task with missing taskId
# Expected error: internal code 1, status code 400
DELETE http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{token}}

### Delete a task with invalid taskId
# Expected error: internal code 4, status code 404
# Expected error: internal code 2, status code 400 (not anymore)
DELETE http://localhost:8000/tasks/a HTTP/2
Authorization: Bearer {{token}}

### Delete a task with taskId from other user
# Expected error: internal code 6, status code 401
DELETE http://localhost:8000/tasks/{{task-user2}} HTTP/2
Authorization: Bearer {{token}}

### Delete task with inexistent taskId
# Expected error: internal code 4, status code 404
GET http://localhost:8000/tasks/abc HTTP/2
Authorization: Bearer {{token}}

### Final get all tasks to verify if change something
# Expected: nothing changed
GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{token}}