### User 2 (testing app)
@token1 = b61cc2a8-0294-4422-a8d8-a02c2f99f183
@token2 = d956cf64-1c2f-46f9-935c-8d8c93399886
@hostnameElastic=localhost
@port=9200

### TASKS ###

### Delete tasks index:
#DELETE /tasks
#Host: {{hostnameElastic}}:{{port}}

### List documents from /tasks:
GET /tasks/_search
Host: {{hostnameElastic}}:{{port}}

### Delete users index:
#DELETE /users
#Host: {{hostnameElastic}}:{{port}}

### List documents from /users:
GET /users/_search
Host: {{hostnameElastic}}:{{port}}


### TESTING TASKS WEB API ###

### Insert a task for user1 (token1)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Insert a task for user1 (token1)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Do class exercise",
    "description": "Implement the task application."
}

### Insert a task for user2 (token2)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Insert a task for user2 (token2)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Do class exercise",
    "description": "Implement the task application."
}


### Get all tasks

GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{token1}}

### Get task 1

GET http://localhost:8000/tasks/snoQP5MBYf62TULrZlMY HTTP/2
Authorization: Bearer {{token1}}

### Update task 1

PUT http://localhost:8000/tasks/snoQP5MBYf62TULrZlMY HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Do class exercise",
    "description": "Reimplement the task application!!!"
}

### Delete task 1

DELETE http://localhost:8000/tasks/s3oRP5MBYf62TULrPVPV HTTP/2
Authorization: Bearer {{token1}}
