### Variables
@token1 = 86130b25-a37e-4f19-9842-549b2fd5bb2c
@token2 = 1a9b3458-fea6-4250-b92b-a3d3b593f446
@hostnameElastic=localhost
@port=9200

### TASKS -- ELASTIC ###

### Delete tasks index:
DELETE /tasks
Host: {{hostnameElastic}}:{{port}}

### List documents from /tasks:
GET /tasks/_search
Host: {{hostnameElastic}}:{{port}}

### Delete users index:
#DELETE /users
#Host: {{hostnameElastic}}:{{port}}

### List documents from /users:
GET /users/_search
Host: {{hostnameElastic}}:{{port}}


### TESTING TASKS WEB API ###

### Insert a task for user1 (token1)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Insert a task for user1 (token1)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Do class exercise",
    "description": "Implement the task application."
}

### Insert a task for user2 (token2)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Task 1",
    "description": "Description of task 1."
}

### Insert a task for user2 (token2)

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Task 2",
    "description": "Description of task 2."
}


### Get all tasks for user1

GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{token1}}

### Get all tasks for user2

GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{token2}}

### Get task for user1

GET http://localhost:8000/tasks/snoQP5MBYf62TULrZlMY HTTP/2
Authorization: Bearer {{token1}}

### Update task for user1

PUT http://localhost:8000/tasks/snoQP5MBYf62TULrZlMY HTTP/2
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "title": "Do class exercise",
    "description": "Reimplement the task application!!!"
}

### Delete task for user1

DELETE http://localhost:8000/tasks/s3oRP5MBYf62TULrPVPV HTTP/2
Authorization: Bearer {{token1}}


### Update task for user2

PUT http://localhost:8000/tasks/JP8zVZMB6oQjLWcDRkDC HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Finish A2 - part 1",
    "description": "Finish the practical assignment 2, part 1, of IPW."
}

### 

PUT http://localhost:8000/tasks/Jf8zVZMB6oQjLWcDaECS HTTP/2
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "title": "Start A2 - part 2",
    "description": "Start to implement the A2 - part 2 of IPW."
}
